```{r}
setwd("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper")
library(ggplot2)
library(RColorBrewer)
library(scales)
library(gggrid)
space<-4 ######
source('/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/collab/leg.R')
colorManual <- c("#377EB8", "#FF7F00", "#E41A1C")


as <- 50
bs <- 25
cs <- 1.5
mytheme<-  theme_bw() +
  theme(
    text = element_text(size = as),
    #panel.grid=element_blank(),
    legend.position = "none",
    plot.title = element_text(size = bs),
    axis.text.x = element_text(size = bs),  # Adjust the size of x-axis labels
    axis.text.y = element_text(size = bs)   # Adjust the size of y-axis labels
  ) 
  
mytheme2<-mytheme+theme(panel.grid=element_blank())


###load data
#setwd('/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/collab/')
pathbig <- "./collab/adjhepth750.RData"
pathsmall <- "./collab/statsnewman.rda"
pathplot <- "./collab/plot"
#load("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/collab_newman_lc.rda")

#load(pathbig)
load(pathbig)
load(pathsmall)
#n = 14845
```

```{r}


n = 5835
library(ggplot2)
library(scales)
library(RColorBrewer)

count95 <- statscount$count95
superscaleUR95 <- count95$superscaleUR95
exactscaleUR95 <- count95$exactscaleUR95

count00 <- statscount$count00
superscaleUR00 <- count00$superscaleUR00
exactscaleUR00 <- count00$exactscaleUR00


b = 750
temp <- 1 - b/n
tau <- sqrt(b*temp)

#UR_G <- graph_to_stats_collab(statscount$adjhep,1,n)
#UR_G <- UR_G$UR_exact

UR_G <- c(2.426973e-06, 3.210259e-07, 6.248317e-09, 3.286984e-11)
rho_hat_GG <- sum(statscount$adjhep)/(n*(n-1))
rho_hat_GG_UR_G <- UR_G*c(rho_hat_GG^(-2),rho_hat_GG^(-3),rho_hat_GG^(-3),rho_hat_GG^(-4))

exactscaleUR95 <- exactscaleUR95 - rho_hat_GG_UR_G
exactscaleUR95  <- exactscaleUR95*tau
names(exactscaleUR95) <- c("twoStar","triangle","threeStar","square")
### plot
smallNetMoment <- exactscaleUR95
v_stats <-  smallNetMoment[1]
tri_stats <-  smallNetMoment[2]
tstar_stats <-  smallNetMoment[3]
square_stats <-  smallNetMoment[4]




exactscaleUR00  <- exactscaleUR00*tau
names(exactscaleUR00) <- c("twoStar","triangle","threeStar","square")
### plot
smallNetMoment00 <- exactscaleUR00
v_stats00 <-  smallNetMoment00[1]
tri_stats00 <-  smallNetMoment00[2]
tstar_stats00 <-  smallNetMoment00[3]
square_stats00 <-  smallNetMoment00[4]
```


```{r}

#### STATS EXACT

setwd("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/collab/plot")

exadf <- as.data.frame(resexa[[2]])[1:2000,]
exadf <- exadf/sqrt(b)
exadf <- sweep(exadf,2,rho_hat_GG_UR_G)
exadf <- exadf*sqrt(b)
colnames(exadf) <- c("twoStar","triangle","threeStar","square")

df <- data.frame(x = exadf$twoStar, y = exadf$triangle)


#####################
p11<-ggplot(df) + 
  geom_point(aes(x = x, y = y),alpha=0.1, colour=colorManual[1]) +   
  stat_density2d(aes(x = x, y = y), colour=colorManual[2]) +   
#  scale_color_manual(values = c('blue')) +
  geom_hline(yintercept = tri_stats, linetype = 'dashed', color = 'black', size = 1) +
  geom_vline(xintercept = v_stats, linetype = 'dashed', color = 'black', size = 1) +  
#  geom_hline(yintercept = tri_stats00, linetype = 'dashed', color = 'black', size = 1) +
#  geom_vline(xintercept = v_stats00, linetype = 'dashed', color = 'black', size = 1) +  
  geom_point(x = v_stats, y = tri_stats, color = colorManual[3], size = 2) +
 # geom_point(x = v_stats00, y = tri_stats00, color = 'brown', size = 2) +
  mytheme+
	  grid_panel(textGrob(y=unit(-0.1,'lines'),x=1,just=c('right','top'),label='X100',gp=gpar(cex=cs)))+
	  grid_panel(textGrob(y=1,x=unit(-0.1,'lines'),just=c('right','top'),label='X10000',gp=gpar(cex=cs)))+
	  coord_cartesian(clip='off')+
#      scale_x_continuous(breaks=c(-50,-25,0,25, 50,75, 100,125, 150,),labels =\(x) sprintf('%2.1f',x/100) ) +  # Use scientific notation for x-axis 
  scale_x_continuous(labels =\(x) sprintf('%2.1f',x/100) ) +   scale_y_continuous(labels =\(x) sprintf('%2.1f',x/10000) )
   
# ggplotGrob(p11)->p11g
# p11g$grobs[[12]]<-v1
# p11g$grobs[[13]]<-v2
# 
# p11g$heights[10]<-unit(space,'cm')
# p11g$widths[6]<-unit(space,'cm')


pdf('out_v_tri.pdf',width=7.7,height=6)
#grid.draw(p11g)
dev.off()
#####################

 
   


df <- data.frame(x = exadf$twoStar, y = exadf$threeStar)

library(ggside)
p12<-ggplot(df) + 
     geom_point(aes(x = x, y = y),alpha=0.1, colour=colorManual[1]) +   
     stat_density2d(aes(x = x, y = y), colour=colorManual[2]) +  
     geom_hline(yintercept = tstar_stats, linetype = 'dashed', color = 'black', size = 0.6) +
     geom_vline(xintercept = v_stats, linetype = 'dashed', color = 'black', size = 0.6) +  
    # geom_hline(yintercept = tstar_stats00, linetype = 'dashed', color = 'black', size = 1) +
    # geom_vline(xintercept = v_stats00, linetype = 'dashed', color = 'black', size = 1) +  
     geom_point(x = v_stats, y = tstar_stats, color = colorManual[3], size = 3) +
    # geom_point(x = v_stats00, y = tstar_stats00, color = 'red', size = 2)+
      mytheme+
	  # grid_panel(textGrob(y=unit(-0.1,'lines'),x=1,just=c('right','top'),label='X100',gp=gpar(cex=cs)),size = bs )+
	  # grid_panel(textGrob(y=1,x=unit(-0.1,'lines'),just=c('right','top'),label='X1000',gp=gpar(cex=cs)),size = bs)+
	  coord_cartesian(clip='off')+
      scale_x_continuous(breaks=c(-50,0, 50, 100)
                         ,labels = c(-50,0, 50, 100)
                         # ,labels =\(x) sprintf('%4.1f',x/100) 
                         ) +  # Use scientific notation for x-axis
      scale_y_continuous(labels =\(x) sprintf('%4.1f',x/1000) )+
      theme(axis.title.x = element_text(size = 30,hjust = 0.35,
                                        margin = margin(t = 10, b = -5)
                                        ),
            axis.title.y = element_text(size = 30,hjust = 0.35,
                                        margin = margin(t = 10, b = -5)
                                        ),
            axis.text.x = element_text(color = "black"),
            axis.text.y = element_text(color = "black"),
            aspect.ratio = 1,  ##这个让它变成正方形的方块
            ggside.panel.border = element_blank(),
            ggside.panel.grid = element_blank(),
            ggside.panel.background = element_blank(),
            ggside.axis.text = element_blank(),
            ggside.axis.ticks = element_blank(),
            ggside.panel.scale = .3
        )+
  xlab("Two star")+
  ylab("Three star")+
  geom_xsidedensity(aes(x = x),
                    ,color = colorManual[1]
                    ,fill=colorManual[1],alpha = 0.65
                    ,size = 0.8
                    ) +
  geom_ysidedensity(aes(y = y),
                    ,color = colorManual[1]
                    ,fill=colorManual[1],alpha = 0.65
                    ,size = 0.8
                    ) +
  geom_xsidevline(xintercept = v_stats,linetype = 'dashed', color = 'black', size = 0.6) +
  geom_ysidehline(yintercept = tstar_stats,linetype = 'dashed', color = 'black', size = 0.6) 
  

  # ggMarginal(aes(x = x, y = y), type = "density", groupColour = TRUE, groupFill = TRUE)

# library(ggExtra)
# ggMarginal(p12, type = "density"
#            ,color = colorManual[1]
#            ,fill=colorManual[1],alpha = 0.8) 
	  
	  
  
# ggplotGrob(p12)->p12g
# p12g$grobs[[12]]<-v1
# p12g$grobs[[13]]<-v3
# 
# p12g$heights[10]<-unit(space,'cm')
# p12g$widths[6]<-unit(space,'cm')

pdf('out_v_3.pdf',width=7.7,height=6)
grid.draw(p12)
dev.off()

```




```{r}

setwd("/Users/mingyuqi/Desktop/Mingyu_network_biometric/network_paper/collab/plot")




exadf <- as.data.frame(resexa[[2]])
exadf <- exadf/sqrt(750)
exadf <- sweep(exadf,2,rho_hat_GG_UR_G)
exadf <- exadf*sqrt(750)
colnames(exadf) <- c("twoStar","triangle","threeStar","square")

# Load the ggplot2 package
library(ggplot2)


# Calculate the quantile of the specific value
quantile_of_value <- (sum(exadf$threeStar <= tstar_stats)) / length(exadf$threeStar)
quantile_of_value

# Plot the histogram with vertical lines and labels
pd11<-ggplot(exadf, aes(x = threeStar)) +
       geom_histogram(bins = 25, fill = colorManual[1], color = "black") + # Adjust the number of bins as needed
       geom_vline(aes(xintercept = tstar_stats), color = "red", linetype = "dashed")+
      mytheme2+
      #labs(x = "three star", y = "density",title="quantile: 0.588")+
      labs(x = "three star", y = "density",title= "percentile: 0.782")+
	  mytheme2+
      grid_panel(textGrob(y=unit(-0.1,'lines'),x=1,just=c('right','top'),label='X1000',gp=gpar(cex=cs)),size = bs )+
	  grid_panel(textGrob(y=1,x=unit(-0.1,'lines'),just=c('right','top'),label='X1000',gp=gpar(cex=cs)),size = bs )+
	  coord_cartesian(clip='off')+
      scale_x_continuous(breaks=c(0,500,1000,1500)
                         ,labels =\(x) sprintf('%4.1f',x/1000)
                         
                         ) +  # Use scientific notation for x-axis
      scale_y_continuous(breaks=c(0,800,1600,2400),labels =\(x) sprintf('%4.1f',x/1000),expand=expansion(c(0,0.05)))


ggplotGrob(pd11)->pd11g
pd11g$grobs[[12]]<-v3
pd11g$heights[10]<-unit(space,'cm')
pd11g$widths[6]<-unit(space,'cm')


pdf('out_threestar_mar.pdf',width=7.7,height=6)
grid.draw(pd11g)
dev.off()
########################



# Calculate the quantile of the specific value
quantile_of_value <- sum(exadf$twoStar <= v_stats) / length(exadf$threeStar)
quantile_of_value



# Your existing setup for plotting
pd12<-ggplot(exadf, aes(x = twoStar)) +
  geom_histogram(bins = 25,  fill = colorManual[1], color = "black") +
  geom_vline(aes(xintercept = v_stats), color = "red", linetype = "dashed")  + 
       labs(x = "three star", y = "density",title= "percentile: 0.324")+
	   mytheme2+
      grid_panel(textGrob(y=unit(-0.1,'lines'),x=1,just=c('right','top'),label='X100',gp=gpar(cex=cs)),size = bs )+
	  grid_panel(textGrob(y=1,x=unit(-0.1,'lines'),just=c('right','top'),label='X1000',gp=gpar(cex=cs)),size = bs )+
	  coord_cartesian(clip='off')+
      scale_x_continuous(breaks=c(-50, 0, 50, 100),labels =\(x) sprintf('%2.1f',x/100) ) +  # Use scientific notation for x-axis
      scale_y_continuous(breaks=c(0,400,800,1200),labels =\(x) sprintf('%2.1f',x/1000),expand=expansion(c(0,0.05)))


ggplotGrob(pd12)->pd12g
pd12g$grobs[[12]]<-v1

pd12g$heights[10]<-unit(space,'cm')
pd12g$widths[6]<-unit(space,'cm')


pdf('out_twostar_mar.pdf',width=7.7,height=6)
grid.draw(pd12g)
dev.off()
#########################


point <- c(v_stats, tstar_stats)

a <- 0.975*v_stats
b <- 1.025*v_stats

df <- exadf[,c(1,3)]

temp <- df[which((df$twoStar < a) & (df$twoStar > b)),]


# Calculate the quantile of the specific value
quantile_of_value <- sum(temp$threeStar<= tstar_stats) / length(temp$threeStar)

quantile_of_value




pd13<-ggplot(temp, aes(x = threeStar,y=..density..)) +
  
  geom_histogram(bins = 13, fill = colorManual[1], alpha = 0.65, color = "black") + # Adjust the number of bins as needed
  #geom_density(color = colorManual[2],size =0.75)+
  # geom_density(fill = colorManual[1], color = "black",alpha=0.65)+
  geom_vline(aes(xintercept = tstar_stats), color = "red", linetype = "dashed",size = 3) + 
	  
  mytheme2+
  labs(x = "Three star | Two star",y = "",title="Percentile: 0.991")+
  theme(axis.title.x = element_text(size = 30,hjust = 0.5,
                                    margin = margin(t = 10, b = -5)
                                    )
        # ,axis.text.y = element_blank()
        # ,axis.ticks.y = element_blank()
        )+
  # theme(plot.title = element_text(hjust = 0.5))+
#       grid_panel(textGrob(y=unit(-0.1,'lines'),x=1,just=c('right','top'),label='X100',gp=gpar(cex=cs)))+
# 	  grid_panel(textGrob(y=1,x=unit(-0.1,'lines'),just=c('right','top'),label='X10',gp=gpar(cex=cs)))+
	  coord_cartesian(clip='off')+
      scale_x_continuous(breaks=c(-200,-100, 0, 100)
                         ,labels=c(-200,-100, 0, 100)
                         # ,labels =\(x) sprintf('%4.1f',x/100) 
                         ) +
  scale_y_continuous( breaks = seq(0,0.006,0.002)
                    ,limits= c(0,0.0071)
                    ,labels = c(0.0,0.2,0.4,0.6 )
                   )
  
  #+  # Use scientific notation for x-axis
      # scale_y_continuous(breaks=c(0,2,4,6),labels =\(x) sprintf('%4.1f',x),expand=expansion(c(0,0.05)))


# zi<-segmentsGrob(y0=0.1,y1=0.9,x0=0.5,x1=0.5,gp=gpar(lwd=2))
# tog<-gtable(width=unit.c(unit(1.6,'cm'),unit(1,'cm'),unit(1.6,'cm')),heights=unit(1.6,'cm'))
# tog<-gtable_add_grob(tog,v3,l=1,t=1)
# tog<-gtable_add_grob(tog,zi,l=2,t=1)
# tog<-gtable_add_grob(tog,v1,l=3,t=1)
# 
# 
# 
# ggplotGrob(pd13)->pd13g
# pd13g$grobs[[12]]<-tog
# 
# pd13g$heights[10]<-unit(space,'cm')
# pd13g$widths[6]<-unit(space,'cm')



pdf('out_threeontwo_cond.pdf',width=7.7,height=6)
grid.draw(pd13)
dev.off()
```
